name: Publish Python Package

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_REPOSITORY: "staging"
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}

permissions:
  contents: read
  actions: read

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist

      - name: List directory contents
        run: ls -la dist/
        shell: bash

      - name: Ensure Cloudsmith CLI is installed
        run: |
          if ! command -v cloudsmith &> /dev/null; then
            echo "Cloudsmith CLI not found! Installing..."
            curl -1sLf 'https://dl.cloudsmith.io/public/cloudsmith/cli/setup.sh' | bash
            sudo apt-get install -y cloudsmith-cli
          fi
          cloudsmith --version
        shell: bash

      - name: Push package to Cloudsmith
        run: |
          PACKAGE_FOUND=$(ls dist/*.tar.gz dist/*.whl 2>/dev/null | wc -l)
          if [ "$PACKAGE_FOUND" -eq "0" ]; then
            echo "No package found to upload"
            exit 1
          fi

          for FILE i
