name: Publish Python Package

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed
  workflow_dispatch:

env:
  CLOUDSMITH_NAMESPACE: ${{ secrets.CLOUDSMITH_NAMESPACE }}  # Accessing secret for namespace
  CLOUDSMITH_REPOSITORY: "staging"  # Replace with your repository name if needed
  CLOUDSMITH_SERVICE_SLUG: ${{ secrets.CLOUDSMITH_SERVICE_SLUG }}  # Accessing secret for service slug

permissions:
  contents: read
  actions: read

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist
          repository: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: 13947721315  # Explicitly using the run_id here

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Cloudsmith CLI via Pip
        run: |
          python -m pip install --upgrade pip
          pip install cloudsmith-cli

      - name: List directory contents
        run: ls -la dist/
        shell: bash

      - name: Debug - Print Cloudsmith Namespace and Repository
        run: |
          echo "CLOUDSMITH_NAMESPACE: ${{ env.CLOUDSMITH_NAMESPACE }}"
          echo "CLOUDSMITH_REPOSITORY: ${{ env.CLOUDSMITH_REPOSITORY }}"

      - name: Push package to Cloudsmith
        run: |
          for file in dist/*.tar.gz dist/*.whl; do
            if [ -f "$file" ]; then
              cloudsmith push python ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_REPOSITORY }} "$file" --republish
            fi
          done
        shell: bash
