name: Publish Python Package

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed
  workflow_dispatch:

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_REPOSITORY: "staging"
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}

permissions:
  contents: read
  actions: read

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Debug GitHub event
        run: echo '${{ toJson(github.event) }}'

      - name: Download artifact
        uses: actions/download-artifact@v4  # Use GitHub's default action
        with:
          name: python-package
          path: dist

      - name: List directory contents
        run: ls -la dist/

      - name: Ensure Cloudsmith CLI is installed
        run: |
          if ! command -v cloudsmith &> /dev/null; then
            echo "Cloudsmith CLI not found! Installing..."
            curl -1sLf 'https://dl.cloudsmith.io/public/cloudsmith/cli/setup.sh' | bash
            sudo apt-get install -y cloudsmith-cli
          fi
          cloudsmith --version

      - name: Push package to Cloudsmith
        run: |
          if ! ls dist/*.tar.gz 1> /dev/null 2>&1; then
            echo "No package found to upload"
            exit 1
          fi
          cloudsmith push python ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_REPOSITORY }} dist/*.tar.gz --republish
